### ISSUE TITLE
Adding issue forms to the repo

### ISSUE THREAD

**Issue by MonarchGitHub** [aman34503/Lets-Talk#2]
I want to add a few issue forms so that it will be convenient for new contributors to open issues. There are already issue templates for this project but they are deprecated now, issue forms instead work way better. I plan to create  **Bug Report**, and **Feature Request** forms. 

**_The Bug Report issue form will have the following fields_**

- **Description of the bug**
- **How to Reproduce**
- **Expected behavior**
- **Urgency indicator**
- **Desktop Info (OS, Version, Browser, etc):**

**_The Feature Request issue form will have the following fields_**

- **Is your feature request related to a problem? Please describe.**
- **Describe the solution you'd like**
- **Describe alternatives you've considered**

**Comment by aman34503** [comment]
yes sure!

**Comment by MonarchGitHub** [comment]
kindly assign me this issue
